[package]
name = "maro"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.53"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "net", "io-util", "signal"] }
